MODEL:
  TYPE: generalized_rcnn
  CONV_BODY: FPN.add_fpn_ResNet152_conv5_body
  NUM_CLASSES: 3
  FASTER_RCNN: True
  CASCADE_RCNN: True
  NUM_RCNN_STAGE: 3
  CLS_AGNOSTIC_BBOX_REG: False
NUM_GPUS: 1
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_decay
  BASE_LR: 0.01
  GAMMA: 0.01
  MAX_ITER: 180000
  STEPS: [0, 120000, 160000]
FPN:
  FPN_ON: True
  MULTILEVEL_ROIS: True
  MULTILEVEL_RPN: True
  RPN_ANCHOR_START_SIZE: 16
  RPN_ASPECT_RATIOS: (0.5, 1, 0.25)
RESNETS:
  STRIDE_1X1: False  # default True for MSRA; False for C2 or Torch models
  TRANS_FUNC: bottleneck_transformation
  NUM_GROUPS: 32
  WIDTH_PER_GROUP: 8
FAST_RCNN:
  ROI_BOX_HEAD: fast_rcnn_heads.add_roi_cascade_2mlp_head
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 7
  ROI_XFORM_SAMPLING_RATIO: 2
CASCADERCNN:
  WEIGHT_LOSS_BBOX_STAGE1: 1.0
  WEIGHT_LOSS_BBOX_STAGE2: 0.5
  WEIGHT_LOSS_BBOX_STAGE3: 0.25
  BBOX_REG_WEIGHTS_STAGE1: (10., 10., 5., 5.)
  BBOX_REG_WEIGHTS_STAGE2: (20., 20., 10., 10.)
  BBOX_REG_WEIGHTS_STAGE3: (30., 30., 15., 15.)
TRAIN:
  WEIGHTS: https://s3-us-west-2.amazonaws.com/detectron/ImageNetPretrained/25093814/X-152-32x8d-IN5k.pkl #./weights/X-152-32x8d-IN5k.pkl #/home/user/workspace/detectron_models/pretrained/R-50.pkl
  DATASETS: ('coco_2014_train',)
  SCALES: (800,)
  MAX_SIZE: 1616
  IMS_PER_BATCH: 1
  BATCH_SIZE_PER_IM: 512
  RPN_PRE_NMS_TOP_N: 2000  # Per FPN level
  RPN_POST_NMS_TOP_N: 1000
  SNAPSHOT_ITERS: 30000
TEST:
  DATASETS: ('coco_2014_minival',)
  SCALE: 800
  MAX_SIZE: 1664
  NMS: 0.6
  RPN_NMS_THRESH: 0.8
  RPN_PRE_NMS_TOP_N: 12000  # Per FPN level
  RPN_POST_NMS_TOP_N: 3000
  BBOX_AUG:
    ENABLED: True
    SCORE_HEUR: UNION
    COORD_HEUR: UNION
    H_FLIP: False
    # SCALES: (200, 300, 400, 500, 600, 700, 800)
    SCALES: (400, 800)
    MAX_SIZE: 2120
    SCALE_H_FLIP: False
    ASPECT_RATIOS: (0.25, 0.5, 1)
    ASPECT_RATIO_H_FLIP: True
  BBOX_VOTE:
    ENABLED: True
    VOTE_TH: 0.85
  SOFT_NMS:
    ENABLED: True
    METHOD: linear
    SIGMA: 0.5
OUTPUT_DIR: .
