MODEL:
  TYPE: generalized_rcnn
  CONV_BODY: FPN.add_fpn_ResNet152_conv5_body
  NUM_CLASSES: 3
  FASTER_RCNN: True
  MASK_ON: False
NUM_GPUS: 1
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_decay
  # 1.44x schedule (note TRAIN.IMS_PER_BATCH: 1)
  BASE_LR: 0.001
  GAMMA: 0.1
  MAX_ITER: 260000
  STEPS: [0, 160000, 220000]
FPN:
  FPN_ON: True
  MULTILEVEL_ROIS: True
  MULTILEVEL_RPN: True
  RPN_ANCHOR_START_SIZE: 16
  RPN_ASPECT_RATIOS: (0.5, 1, 0.25)
RESNETS:
  STRIDE_1X1: False  # default True for MSRA; False for C2 or Torch models
  TRANS_FUNC: bottleneck_transformation
  NUM_GROUPS: 32
  WIDTH_PER_GROUP: 8
FAST_RCNN:
  ROI_BOX_HEAD: fast_rcnn_heads.add_roi_2mlp_head
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 7
  ROI_XFORM_SAMPLING_RATIO: 2
TRAIN:
  WEIGHTS: ./weights/X-152-32x8d-IN5k.pkl #https://s3-us-west-2.amazonaws.com/detectron/ImageNetPretrained/25093814/X-152-32x8d-IN5k.pkl
  DATASETS: ('coco_2014_train', )
  SCALES: (576, 832,)  # Scale jitter
  CASCADE_RCNN: True
  CASCADE_THRESHOLDS: 0.5, 0.6, 0.7
  MAX_SIZE: 1664
  IMS_PER_BATCH: 1
  BATCH_SIZE_PER_IM: 512
  RPN_PRE_NMS_TOP_N: 6000  # Per FPN level
  RPN_POST_NMS_TOP_N: 1000
  SNAPSHOT_ITERS: 20000
TEST:
  DATASETS: ('coco_2014_minival',)
  SCALE: 832
  NMS: 0.5
  BBOX_VOTE:
    ENABLED: True
    VOTE_TH: 0.9
  RPN_PRE_NMS_TOP_N: 10000  # Per FPN level
  RPN_POST_NMS_TOP_N: 1000
  BBOX_AUG:
    ENABLED: True
    SCORE_HEUR: UNION
    COORD_HEUR: UNION
    H_FLIP: True
    SCALES: (100, 200, 400, 600, 800)
    MAX_SIZE: 1000
    SCALE_H_FLIP: True
    SCALE_SIZE_DEP: False
    ASPECT_RATIOS: (0.25, 0.5, 1, 2)
    ASPECT_RATIO_H_FLIP: False
OUTPUT_DIR: .
